name: Build and Test

on: [push, pull_request]

jobs:
  build:
 
    runs-on:  windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Setup VSTest
      uses: Setup-VSTest@v1
     
    - name: Restore NuGet Packages
      run: nuget restore ./Zoo_Simulator/Zoo_Simulator.sln
 
    - name: Build and Publish Web App
      run: msbuild ./Zoo_Simulator/Zoo_Simulator.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: bin\Release\Publish

    - name: Run Tests
      run: vstest.console.exe .\\Zoo_Simulator_Tests\bin\Release\net8.0\Zoo_Simulator_Tests.dll
