name: Build and Test

on: [push, pull_request]

jobs:
  build:
 
    runs-on:  windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@latest

      - name: Setup NuGet
        uses: NuGet/setup-nuget@latest
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@latest

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore ./Zoo_Simulator/Zoo_Simulator.sln
 